name: Update ETF Data (Weekdays 4PM AEST)
on:
  schedule:
    - cron: "0 6 * * 1-5"  # 4 PM AEST (06:00 UTC), Mon-Fri
  workflow_dispatch:  # Manual trigger

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"  # Specify major.minor (GitHub may not have patch versions like 3.13.5)
      - run: pip install yfinance pandas
      - run: python update_etfs.py
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docs/data.json
          git commit -m "Auto-update ETF data" || echo "No changes to commit"
          git push